= Client
:toc:
:icons: font

This project was generated using https://github.com/angular/angular-cli[Angular CLI] version 21.0.2.

== Development server

To start a local development server, run:

[source,bash]
----
ng serve
----

Once the server is running, open your browser and navigate to `http://localhost:4200/`. The application will automatically reload whenever you modify any of the source files.

== Code scaffolding

Angular CLI includes powerful code scaffolding tools. To generate a new component, run:

[source,bash]
----
ng generate component component-name
----

For a complete list of available schematics (such as `components`, `directives`, or `pipes`), run:

[source,bash]
----
ng generate --help
----

== Building

To build the project run:

[source,bash]
----
ng build
----

This will compile your project and store the build artifacts in the `dist/` directory. By default, the production build optimizes your application for performance and speed.

== Running unit tests

To execute unit tests with the https://vitest.dev/[Vitest] test runner, use the following command:

[source,bash]
----
ng test
----

== Running end-to-end tests

For end-to-end (e2e) testing, run:

[source,bash]
----
ng e2e
----

Angular CLI does not come with an end-to-end testing framework by default. You can choose one that suits your needs.

== Additional Resources

For more information on using the Angular CLI, including detailed command references, visit the https://angular.dev/tools/cli[Angular CLI Overview and Command Reference] page.
