@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "A user of the Boat Manager system.")
System(boat_manager, "Boat Manager", "Allows users to manage boats and related data.")

Rel(user, boat_manager, "Uses")
@enduml
